### ISSUE TITLE
Notification: Changes in "binary types" and "binary interop"

### ISSUE THREAD

**Issue by mezoni** [DirectMyFile/coreutils#2]
Your project uses "binary types".
New version of "binary types" available and it can affect your project if you declare foreign functions manually through the `DynamicLibrary.function()`.

Also now available other useful features that you can use in your projects.
Expressions in declarations:

``` c
enum EnumA {Enum_A};
enum EnumB {Enum_B = Enum_A + 5 + sizeof(enum EnumA)};

typedef int ia10[8 + 2];
typedef int ia1[sizeof(int) >> 2];
typedef int ia4[sizeof(ia1)];
```

Enumerators now available through `BinaryTypeHelper.enumerators`
Declare:

``` c
enum Number {ZERO, ONE, FIVE = ZERO + 5};
```

Use:

``` dart
var five = helper.enumerators["FIVE"];
```

Binary generator will be updated soon for new features.

**Comment by azenla** [comment]
Nice! :)
